---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by seancheey.
--- DateTime: 9/30/20 2:20 AM
---
data:extend {
    {
        type = "custom-input",
        name = "build-transport-line",
        key_sequence = "SHIFT + mouse-button-1"
    },
    {
        type = "custom-input",
        name = "build-transport-line-no-underground",
        key_sequence = "CONTROL + SHIFT + mouse-button-1"
    },
    {
        type = "custom-input",
        name = "select-line-starting-point",
        key_sequence = "SHIFT + mouse-button-2"
    }
}