---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by seancheey.
--- DateTime: 9/30/20 2:20 AM
---
data:extend {
    {
        type = "custom-input",
        name = "build-transport-line",
        key_sequence = "CONTROL + mouse-button-1"
    },
    {
        type = "custom-input",
        name = "build-transport-line-no-underground",
        key_sequence = "CONTROL + SHIFT + mouse-button-1"
    },
    {
        type = "custom-input",
        name = "build-transport-line-prefer-ground",
        key_sequence = "CONTROL + ALT + mouse-button-1"
    },
    {
        type = "custom-input",
        name = "select-line-starting-point",
        key_sequence = "CONTROL + mouse-button-2",
        alternative_key_sequence = "CONTROL + SHIFT + mouse-button-2"
    },
    {
        type = "custom-input",
        name = "toggle-waypoint-mode",
        key_sequence = "CONTROL + Q",
    },
    {
        type = "shortcut",
        name = "toggle-waypoint-mode",
        toggleable = true,
        icon = {
            filename = "__BeltRouter__/icon/waypoint-mode.png",
            size = {283,278},
        },
        action = "lua"
    }
}