---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by seancheey.
--- DateTime: 10/6/20 1:03 AM
---

--- Core abstract class for path finding
--- @class PathFinder
--- @field startingEntity LuaEntity
local PathFinder = {}

function PathFinder:new(o)
    o = o or {}
    setmetatable(o, self)
    self.__index = self
end

