---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by seancheey.
--- DateTime: 10/13/20 9:04 PM
---

--- @type ArrayList
local ArrayList = require("__MiscLib__/array_list")

--- @class EntitySelectionInfo
--- @field entity LuaEntity
--- @field polygonId number

--- @class SelectionQueue
--- @field queue ArrayList|EntitySelectionInfo[] I use arraylist here since player won't select too much belts at the same time and linked list has extra memory cost
--- @field playerIndex player_index
--- @type SelectionQueue
local SelectionQueue = {}
SelectionQueue.__index = SelectionQueue

--- @return SelectionQueue
function SelectionQueue:new(playerIndex)
    --- @type SelectionQueue
    local o = {}
    setmetatable(o, self)
    o.playerIndex = playerIndex
    o.queue = ArrayList.new()
    return o
end

--- @param entity LuaEntity
function SelectionQueue:push(entity)
    self.queue:add(entity)
end

--- @return LuaEntity
function SelectionQueue:pop()
    if #self.queue > 0 then
        return self.queue:popLeft()
    end
end

function SelectionQueue:remove(index)
    return self.queue:pop(index)
end

function SelectionQueue:__len()
    return #self.queue
end

return SelectionQueue