---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by seancheey.
--- DateTime: 10/10/20 3:50 AM
---

--- @class EntityTransportType
--- @type EntityTransportType
local EntityTransportType = {}

EntityTransportType.onGround = "onGround"
EntityTransportType.underground = "underground"
EntityTransportType.splitter = "splitter"
EntityTransportType.pump = "pump"
EntityTransportType.pipe = "pipe"

return EntityTransportType
