---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by seancheey.
--- DateTime: 10/10/20 3:50 AM
---

--- @class TransportLineType
--- @type TransportLineType
local LineType = {}

LineType.fluidLine = "fluidLine"
LineType.itemLine = "itemLine"

return LineType